#!/usr/bin/env python3
# coding=UTF-8

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fibonacci(n):
    f, f1, f2 = 0, 1, 2
    l = [2]
    if n == 1:
        return 0
    elif n == 2:
        return 2
    else:
        while f < n:
            f = f1 + f2
            if f % 2 == 0:
                l.append(f)
            f1, f2 = f2, f
    return sum(l)


print(fibonacci(2))
